name: Release
on:
  release:
    types: [published, edited]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: ./lighthouserc.json
          githubToken: ${LHCI_GITHUB_TOKEN}
      - name: Save results as Artifact
        uses: actions/upload-artifact@v1
        with:
          name: lighthouse-results
          path: '.lighthouseci'
