name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Run a multi-line script
      run: |
        echo Builded with NPM.
        
  audit:
    runs-on: macos-latest
    needs: [build]

    steps:
      - name: Google Lighthouse Audit
        run: echo Audited with Lighthouse!
